Update trigger_jenkins_label.yml

diff --git a/.github/workflows/trigger_jenkins_label.yml b/.github/workflows/trigger_jenkins_label.yml
--- a/.github/workflows/trigger_jenkins_label.yml
+++ b/.github/workflows/trigger_jenkins_label.yml
@@ -12,10 +12,10 @@ jobs:
     steps:
       - name: Check PR Label
         id: check_label
-        run: echo ::set-output name=label::${{ github.event.label.name }}
+        run: echo "LABEL=${{ github.event.label.name }}" >> $GITHUB_ENV
 
       - name: Trigger Jenkins Job
-        if: steps.check_label.outputs.label == 'Check'
+        if: env.LABEL == 'Check'
         run: |
           JENKINS_USERNAME=${{ secrets.JENKINS_USERNAME }}
           JENKINS_TOKEN=${{ secrets.JENKINS_API_TOKEN }}
@@ -23,7 +23,7 @@ jobs:
           curl -X POST -u $JENKINS_USERNAME:$JENKINS_TOKEN $JOB_URL
           BUILD_NUMBER=$(curl -X POST -u $JENKINS_USERNAME:$JENKINS_TOKEN http://16.170.212.178:8080/job/Pull_and_merge | jq -r '.number')
           echo "The Jenkins build number is $BUILD_NUMBER"
-          echo "::set-output name=build_number::$BUILD_NUMBER"
+          echo "BUILD_NUMBER=${BUILD_NUMBER}" >> $GITHUB_ENV
 
       - name: Check Jenkins Build Status
         id: check_build_status
@@ -33,19 +33,18 @@ jobs:
           BUILD_STATUS=$(curl -X GET -u $JENKINS_USERNAME:$JENKINS_TOKEN "http://16.170.212.178:8080/job/Pull_and_merge/$BUILD_NUMBER/api/json" | jq -r '.result')
           echo "Jenkins Build Status: $BUILD_STATUS"
           if [[ "$BUILD_STATUS" == "SUCCESS" ]]; then
-            echo "::set-output name=build_result::success"
+            echo "BUILD_RESULT=success" >> $GITHUB_ENV
           else
-            echo "::set-output name=build_result::failure"
-            exit 1  
+            echo "BUILD_RESULT=failure" >> $GITHUB_ENV
+            exit 1
           fi
 
       - name: Set GitHub Check Status
-        id: set_check_status
-        if: steps.check_label.outputs.label == 'Check'
+        if: env.LABEL == 'Check'
         run: |
           GITHUB_TOKEN=${{ secrets.GH_TOKEN }}
           PR_NUMBER=${{ github.event.pull_request.number }}
-          BUILD_RESULT=${{ steps.check_build_status.outputs.build_result }}
+          BUILD_RESULT=${{ env.BUILD_RESULT }}
           if [[ "$BUILD_RESULT" == "success" ]]; then
             CHECK_STATUS="completed"
             CHECK_CONCLUSION="success"
