Update trigger_jenkins_label.yml

diff --git a/.github/workflows/trigger_jenkins_label.yml b/.github/workflows/trigger_jenkins_label.yml
--- a/.github/workflows/trigger_jenkins_label.yml
+++ b/.github/workflows/trigger_jenkins_label.yml
@@ -24,6 +24,7 @@ jobs:
           BUILD_NUMBER=$(curl -X POST -u $JENKINS_USERNAME:$JENKINS_TOKEN http://51.20.12.98:8080/job/Pull_and_merge | jq -r '.number')
           echo "The Jenkins build number is $BUILD_NUMBER"
           echo "::set-output name=build_number::$BUILD_NUMBER"
+
       - name: Check Jenkins Build Status
         id: check_build_status
         run: |
@@ -35,6 +36,7 @@ jobs:
             echo "::set-output name=build_result::success"
           else
             echo "::set-output name=build_result::failure"
+            exit 1  # Fail the GitHub Action if the Jenkins build fails
           fi
 
       - name: Set GitHub Check Status
@@ -64,4 +66,3 @@ jobs:
               \"conclusion\": \"$CHECK_CONCLUSION\"
             }" \
             "https://api.github.com/repos/${{ github.repository }}/check-runs"
-          
